SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS market_note;
DROP TABLE IF EXISTS demographics;
DROP TABLE IF EXISTS demand_structure;
DROP TABLE IF EXISTS price_info;
DROP TABLE IF EXISTS property_type;
DROP TABLE IF EXISTS region;

SET FOREIGN_KEY_CHECKS = 1;